### ISSUE TITLE
建议添加天境mod和天境：遗失之物

### ISSUE THREAD

**Issue by THOKA-PRINCESS** [mrsongbyssgs/Tudou-server#3]
[aether-1.20.1-1.0.0-beta.1.4-neoforge.zip](https://github.com/mrsongbyssgs/Tudou-server/files/13470699/aether-1.20.1-1.0.0-beta.1.4-neoforge.zip)
[lost_aether_content-1.20.1-1.2.2 (2).zip](https://github.com/mrsongbyssgs/Tudou-server/files/13470703/lost_aether_content-1.20.1-1.2.2.2.zip)
以上是两个mod，jar在zip里面，测试了在土豆客户端上均可以加载，基本功能均正常，具体有没有bug我还没试出来，虽然写的是neoforge，但亲测在forge上也可以运行，希望加到服务器里面

**Comment by mrsongbyssgs** [comment]
已通过此申请，请耐心等待投票
